cryptol-remote-api/src/CryptolServer.hs

The structure currently represented only goes one level deep—contained errors (notably parse, renamer, and type errors) are embedded as lists of `pretty`ed strings. In future, this could easily be altered to provide deeper structure—should this PR be merged before then?

Provide JSON structure and individual error IDs to Cryptol errors

---

python/argo-python.cabal
python/hs-test/Main.hs
python/saw/__init__.py
tasty-script-exitcode/src/Test/Tasty/HUnit/ScriptExit.hs

Fixes #42. Along the way:
* The limitation on one-to-one extension to `TestLang` mapping has been lifted: many `TestLang`s can be defined for any given file extension and all will be considered.
* MyPy has been added as a `TestLang` in the `tasty-script-exitcode` package.

Cabal test mypy

---

argo/argo.cabal
argo/src/Argo/DefaultMain.hs
cryptol-remote-api/cryptol-remote-api.cabal
cryptol-remote-api/cryptol-remote-api/Main.hs
saw-remote-api/saw-remote-api.cabal
saw-remote-api/saw-remote-api/Main.hs

While doing this, the substantially similar main actions in both servers were consolidated into one, reducing duplication, and the usage information blurb was greatly improved.

Add a --public flag to bind a public socket

---

argo/src/Argo/HistoryWrapper.hs
python/saw/connection.py

We have not yet ruled out [] so as to not break client code.
Fixes #54.

Allow JSON null for the initial state

---

argo/argo.cabal
argo/src/Argo.hs
examples/salsa20.py
examples/swap.py
python/argo/connection.py
python/saw/__init__.py
python/saw/connection.py
python/saw/dashboard.py
python/saw/llvm.py
saw-remote-api/test-scripts/salsa20_easy.py
stack.yaml

Fixes #58 by creating a separate interface for `View`s on the progress of a proof, and adapts the myxine-based implementation of the dashboard for this approach, merging it in to replace the old Python-file-server version.
This PR is pointed to merge into #72 rather than master because the two form a cohesive whole together, and I think if they both make sense, we should merge them all at once (though they're separated into two PRs for legibility).

Detangled dashboard

---

argo/src/Argo.hs
examples/salsa20.py
examples/swap.py
python/argo/connection.py
python/argo/interaction.py
python/saw/__init__.py
python/saw/dashboard.py
python/saw/exceptions.py

Working towards addressing #59 (but not resolving it)...
The Argo protocol now transmits the full captured stdout/err of the
method invoked back to the client, which may do with it what they
please. In the case of the Python client to the SAW server, this
information is exposed in the exceptions thrown, and in particular, to
the View implementations that can track and display this information as
if it was coming natively from the Python process.
To use this functionality in the Python client, add a `View` for it, as the salsa20 and swap examples do:
```python
connect("cabal -v0 v2-run exe:saw-remote-api")
view(DebugLog(err=None))
view(LogResults())
```
The two optional named parameters for `DebugLog` are `out` and `err` and direct the stdout/stderr of the invoked method to either the same …

Modify Argo protocol and Python SAW client to track stdout/err

---

argo/src/Argo/DefaultMain.hs

Set the PR into this branch because that's what saw-script is currently pulling in as a submodule.

Add hostname option

---

python/cryptol/cryptoltypes.py

Should fix https://github.com/GaloisInc/argo/issues/110 - I've got a cryptol-remote-api test locally that successfully uses it, but nothing in this repo ... =\

fix: allow BitVector param type to Cryptol fns

---

NEWS.rst
argo/src/Argo.hs
argo/src/Argo/DefaultMain.hs
argo/src/Argo/Socket.hs

This turns off debug logging to stderr by default, and adds a command-line option to enable it.
To future-proof the interface, logging is enabled by specifying a destination (which must be stderr for now) rather than by a Boolean flag.

Make stderr logging optional

---

argo/src/Argo.hs
argo/src/Argo/DefaultMain.hs
argo/src/Argo/Netstring.hs
argo/src/Argo/Socket.hs

Now logging _should_ be disabled for for all transport modes unless
explicitly requested.

Make logging more consistent

---

argo/src/Argo/DefaultMain.hs
file-echo-api/file-echo-api.cabal
file-echo-api/file-echo-api/Main.hs
file-echo-api/src/FileEchoServer.hs
file-echo-api/test-scripts/file-echo-tests.py

Provide a more flexible "main" that allows Argo apps to enrich the
collection of allowed command-line arguments, and then construct the
application and initial state based on them.
This is part of https://github.com/GaloisInc/cryptol/issues/1009, and should probably not be merged until the Cryptol side has been implemented.

Allow Argo apps to extend the command-line interface

---

argo/src/Argo.hs
argo/src/Argo/DefaultMain.hs
argo/src/Argo/Socket.hs
file-echo-api/file-echo-api/Main.hs
file-echo-api/test-scripts/file-echo-tests.py

This allows `argo` to work on a read-only file system. Or, at least, it should. If we discover any other file writes in the codebase, we can turn them off with the same option.
The one open question I have is whether the read-only option and the logger should be packaged together into some sort of more general record of options.

Add an option to avoid using `hCapture`

---

NEWS.rst
argo/argo.cabal
argo/src/Argo.hs
argo/src/Argo/DefaultMain.hs
argo/src/Argo/Doc.hs
argo/src/Argo/Doc/Protocol.hs
argo/src/Argo/Doc/ReST.hs
file-echo-api/file-echo-api/Main.hs
file-echo-api/src/FileEchoServer.hs

This is a breaking change for client applications, but not for their clients.
The idea is to gently guide application implementors into adding documentation at various points. Right now, it renders to ReST, but it can be extended to render to other formats in the future. I hope that it can be used to generate what Sphinx is getting as input, and that it will ease the task of keeping docs and code in sync.
Outputting plain text is an easy extension, while Markdown might be a bit harder due to the inability to arbitrarily nest Markdown docs. A best-effort "markdown" would be easy as well, though.

Initial version of inline application documentation.

---

argo/argo.cabal
argo/src/Argo.hs
argo/src/Argo/DefaultMain.hs
argo/src/Argo/ServerState.hs
argo/src/Argo/Socket.hs
file-echo-api/README.rst
file-echo-api/file-echo-api/Main.hs
file-echo-api/src/FileEchoServer.hs
file-echo-api/test-scripts/file-echo-tests.py
file-echo-api/test/Test.hs
python/argo/connection.py
python/argo/interaction.py

This PR modifies Argo servers to guarantee a bound on memory usage.
This is accomplished by:
1. keeping only the initial server state cached indefinitely,
2. keeping alive a (customizable) number of recently used states
while evicting others from the cache when it fills (along with
any no longer in-use file contents loaded from disk), and
3. allows states to be explicitly pinned in the cache, which would
keep them in memory until they are explicitly unpinned.
The main cost of this change is that arbitrary states no longer
in cache cannot be "replayed" or "resurrected" automatically when
a request mentioning them is received once they are evicted from the cache
(such a state would either have to be manually pinned or rebuilt
by the client through standard interactions from a live state). …

feat: bound memory usage by server

---

.github/workflows/ci.yml
python/cryptol/test/test_bitvector.py

This is a fairly straightforward process for the most part, as most of the errors are caused by either:
* Assertion functions not having type signatures
* Test cases with ill typed inputs not being annotated with `#type: ignore`
One tricky corner case is this test case:
```py
self.assertUnOpExpected(
lambda b: b & (2 ** b.size() - 1),
lambda b: b)
```
Surprisingly, `mypy` complains about the `2 ** b.size()` part:
```
cryptol/test/test_bitvector.py:148: error: Returning Any from function declared to return "BV"
```
I'm surprised that `mypy` couldn't figure this one out, but nevertheless, I worked around this by using `cast(int, 2 ** b.size() - 1)`.
Fixes #149.

Fix mypy errors in test_bitvector.py

---

argo/argo.cabal
argo/src/Argo.hs
argo/src/Argo/DefaultMain.hs
argo/src/Argo/ServerState.hs
file-echo-api/file-echo-api.cabal
file-echo-api/file-echo-api/Main.hs
file-echo-api/mutable-file-echo-api/Main.hs
file-echo-api/src/FileEchoServer.hs
file-echo-api/src/MutableFileEchoServer.hs
python/argo_client/interaction.py
python/setup.py
python/tests/test-data/base.txt
python/tests/test_file_echo_api.py
python/tests/test_file_echo_interaction.py
python/tests/test_mutable_file_echo_api.py

This PR adds support for servers with mutable state (like SAW's). This is accomplished as follows:
1. mkApp (i.e., the creation of an Argo server app) takes a `StateMutability` in the `AppOpts`, which indicates if initial states must be re-created for every new use (`MutableState`) or whether the same one can be reused for each new initial request (`PureState`).
2. `StateID` usage (for non-initial states) is now destructive, which will make preventing mutation in the underlying server from affecting other requests trivial. I.e., a when a command is made from a particular (non-initial) `StateID`, that `StateID` is destroyed and is no longer reachable, and a new `StateID` is associated with the resulting state from that request (regardless of whether or not the state actually changed). Down …

feat: mutable file-echo-api with tests

---

argo/src/Argo.hs
argo/src/Argo/Doc.hs
file-echo-api/README.rst
file-echo-api/src/FileEchoServer.hs
file-echo-api/src/MutableFileEchoServer.hs

Currently, the `DescribedParams` class allows for declaring the documentation for the _parameters_ of methods, but not the _results_. This makes it insufficient for generating the sorts of documentation like what is written [here](https://github.com/GaloisInc/saw-script/blob/7bb93c9b5c08422a49017e49772d8d2db3ff8fb0/saw-remote-api/docs/old-Saw.rst#running-proof-scripts) in the handwritten SAW remote API docs.
This is an attempt at augmenting the `DescribedParams` class to allow documenting result values in addition to parameters. Some of the highlights are:
* The class has now been renamed to `DescribedMethod` to reflect its more general purpose.
* `DescribedMethod` now has two type parameters: `params` (which existed before) and `result`. There is a `params -> result` functional …

RFC: Support autogenerated documentation for method results, in addition to parameters

---

.github/workflows/ci.yml

The workflow was previously relying on an Ubuntu GHC PPA being pre-added on each GitHub Actions runner, but this no longer happens after actions/virtual-environments#3268. Better to just use `haskell/actions/setup` to install GHC instead, which does the hard work of figuring out how to install GHC for us.

CI: Use haskell/actions/setup to install GHC

---

.github/workflows/ci.yml
argo/argo.cabal
file-echo-api/file-echo-api.cabal

Also add a GHC 9.0.1 configuration in CI.

Bump upper version bounds on base to allow building with GHC 9.0

---

argo/src/Argo.hs
argo/src/Argo/ServerState.hs
file-echo-api/file-echo-api.cabal
file-echo-api/file-echo-api/Main.hs
file-echo-api/mutable-file-echo-api/Main.hs
file-echo-api/src/FileEchoServer.hs
file-echo-api/src/MutableFileEchoServer.hs
python/tests/test_file_echo_api.py
python/tests/test_mutable_file_echo_api.py

This PR adds the ability to interrupt all active threads serving requests in the server.
Design notes:
+ For simplicity's sake, an interrupt is a server-wide event and cannot target specific requests. This seems reasonable as an initial constraint given that the `MVars` guarding the server state currently only allow one active request at a time. I.e., things are already fairly linear already so this shouldn't complicate any workflows.
+ For servers with *immutable state*, active requests which are cancelled have no observable effects since the updated state is only recorded upon completion of the request.
+ For servers with *mutable state* (or mutable _portions_ of state), effects (i.e., `IO`) from an interrupted thread may be observed since they cannot be rolled back in any meaningful …

feat: server can now be interrupted, cancelling all active requests

---

argo/src/Argo.hs
argo/src/Argo/DefaultMain.hs
python/CHANGELOG.md
python/argo_client/connection.py
python/setup.py
python/tests/test_file_echo_api.py

This PR adds basic logging which can be toggled for both the argo client 
and server, s.t. each RPC transmission (TX) and reception (RX) is emitted
on a single line to the specified file/handle.
Tests ensuring this works as expected for each transport method available
have also been added to the python test suite.
The underlying goal here is to make it easier to debug server/client interactions
(especially in non-trivial deployment situations).
Any feedback/critique/etc on logging techniques used (e.g., is writing to a file
with `Text.appendFile` reasonable for file logging? etc) welcome!

feat: server and client logging options for RPC tx/rx

---

argo/src/Argo.hs
argo/src/Argo/DefaultMain.hs
argo/src/Argo/ServerState.hs
file-echo-api/file-echo-api/Main.hs
file-echo-api/mutable-file-echo-api/Main.hs
file-echo-api/src/FileEchoServer.hs
python/CHANGELOG.md
python/argo_client/connection.py
python/setup.py
python/tests/test_file_echo_api.py
python/tests/test_mutable_file_echo_api.py

Makes it so that the handling of a notification cannot be interrupted/interleaved with new commands/queries/notifications. This may be enough to fix https://github.com/GaloisInc/cryptol/issues/1261
Tweaking the default state eviction policy to remove older requests automatically instead of reject new ones if the server is full (thus removing the need for scripts to call `reset` when connecting) may also be helpful.

feat: notifications delay new request handling while running

---

python/CHANGELOG.md
python/argo_client/connection.py
python/setup.py

6ca9206191197c938b9e63e4d06a65ef00092751 did not end up including changes that require a version bump for the argo client.

chore: undo argo-client version bump

---

.github/workflows/ci.yml
argo/argo.cabal
file-echo-api/file-echo-api.cabal

This raises the upper version bounds on `base` and `bytestring` to allow building with GHC 9.2.

Allow building with GHC 9.2

---

.github/workflows/ci.yml
python/poetry.lock
python/pyproject.toml

The `typed-ast` package is being end-of-life'd soon. See python/typed_ast#179. Moreover, it is causing issues when building with Python 3.11+. See GaloisInc/cryptol#1491.  Thankfully, `typed-ast` is no longer required if you use sufficiently new versions of `mypy` and Python. This patch raises the lower version bounds to make it possible to shed the `typed-ast` dependency entirely.

Python: Avoid `typed-ast` dependency

---

.github/workflows/ci.yml

The version we were previously using (1.1.11) is affected by this bug, causing invocations of Poetry to fail:
https://github.com/ionrock/cachecontrol/issues/292

CI: Upgrade Poetry version

---

python/pyproject.toml

This is motivated by a desire to switch away from `setuptools`, which has some unfortunate interactions with static analysis tools.

Python: Use poetry.core.masonry.api as build-backend

---

.github/workflows/ci.yml
argo/argo.cabal
argo/src/Argo/Doc.hs
file-echo-api/file-echo-api.cabal

This is a simple matter of bumping version bounds.
Along the way, I also fixed a warning uncovered with recent GHCs and updated the CI.

Allow building with GHC 9.6

---

.github/workflows/ci.yml
argo/argo.cabal
file-echo-api/file-echo-api.cabal
python/tests/test_file_echo_api.py

This bumps the upper version bounds on the `base`, `bytestring`, `scotty`, `text`, and `vector` libraries in order to support building with versions that are required by GHC 9.8.

Allow building with GHC 9.8

---

.github/workflows/ci.yml
README.rst
argo/argo.cabal
python/poetry.lock
python/pyproject.toml

Python: Pin `types-requests` version

---

python/CHANGELOG.md
python/argo_client/connection.py
python/argo_client/netstring.py
python/pyproject.toml

This change also makes the netstring parser more robust to support the way that it's used in the network loop

Using blocking network IO to avoid busy-wait
